default:
  image: alpine:latest
  before_script:
    - apk add --no-cache docker
    - docker info

build_image:
  stage: build
  script:
    - docker build -t dashboard-profiling -f docker/development/Dockerfile .
