name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    # Generate a timestamp and store it as an environment variable
    - name: Set image tag
      run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

    # Build the Docker image
    - name: Build the Docker image
      run: docker build . --file prod.Dockerfile --tag shalahuddinabdulaziz/fanfare:${{ env.IMAGE_TAG }}

    # Push the Docker image to Docker Hub
    - name: Push the Docker image
      run: |
        docker tag shalahuddinabdulaziz/fanfare:${{ env.IMAGE_TAG }} shalahuddinabdulaziz/fanfare:latest
        docker push shalahuddinabdulaziz/fanfare:${{ env.IMAGE_TAG }}
        docker push shalahuddinabdulaziz/fanfare:latest
